config/routes.rb
Timemanagement::Application.routes.draw do




	
	
	resources :users do
		resources :projects do
			member do
				get 'finish'
				get 'resume'
			end
			resources :shifts
		end
	end
	
	root :to => "sessions#home"
	match "signup", :to => "users#new", via: [:get, :post]
	match "login", :to => "sessions#login", via: [:get]
	match "login", :to => "sessions#login_attempt", via: [:post]
	get "logout", :to => "sessions#logout"
	get "dashboard", :to => "sessions#dashboard"
	get "profile", :to => "sessions#profile"
	get "statistics", :to => "sessions#statistics"

	get 'auth/:provider/callback' => 'sessions#login_auth'
	get 'auth/failure' => 'sesions#failure'
	





end

app/models/shift.rb
class Shift < ActiveRecord::Base
	belongs_to :project

	validates :start_date, :presence => true
	validates :end_date, :presence => true
	validates_datetime :end_date, :after => :start_date

	before_save :calc_duration

	def to_s
		@text_duration = "From #{start_date.to_s(:long)} to #{end_date.to_s(:long)} (#{duration} hours)"
		return @text_duration
	end

	def calc_duration
		self.duration = ((end_date - start_date)/3600.0).round(2)
	end

end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController

	before_filter :check_user, :only => [:show, :new, :create, :destroy]

	def index
		@project = Project.find params[:project_id]
		@shifts = Shift.where('project_id = ?',@project.id)
	end

	def new
		@project = Project.find params[:project_id]
		@shift = Shift.new
	end

	def create
		@project = Project.find params[:project_id]
		@user = User.find params[:user_id]
		#used params[:shift].permit! so the full Shift hash is permitted, since datetime variables create sub-hashes
		@shift = Shift.new(params[:shift].permit!) 
		if @shift.save
			flash[:notice] = "Shift added successfully."
			flash[:color] = "valid"
			redirect_to "/users/#{@user.id}/projects/#{@project.id}"
		else
			flash[:notice] = "Invalid shift data"
			flash[:color] = "invalid"
			render "new"
		end
	end	

	def destroy
		@project = Project.find params[:project_id]
		@user = User.find params[:user_id]
		Shift.destroy(params[:id])
		flash[:notice] = "Shift deleted successfully."
		flash[:color] = "valid"
		redirect_to "/users/#{@user.id}/projects/#{@project.id}/shifts"
	end

	def update
		@shift = Shift.find(params[:id])
		@project = Project.find(@shift.project_id)
		if @shift.update(params[:shift].permit!)
			redirect_to "/users/#{@project.user_id}/projects/#{@project.id}/shifts"
		else
			render 'edit'
		end
	end

	def edit
		@project = Project.find params[:project_id]
		@user = User.find params[:user_id]
		@shift = Shift.find(params[:id])
	end

	def check_user
		#check that user in session is the same as user in url
		if session[:user_id].to_i == params[:user_id].to_i
			return true
		elsif session[:user_id]
			redirect_to(:controller => 'sessions' , :action => 'dashboard')
			return false
		else
			redirect_to(:controller => 'sessions' , :action => 'login')
			return false
		end
	end

	rescue_from ActiveRecord::RecordNotFound do
		flash[:notice] = 'The object you tried to access does not exist'
		redirect_to dashboard_path
	end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/index.html.haml
%p= "Shifts for project #{@project.name}"

%ul
	- @shifts.each do |shift|
		%li
			= shift.to_s
			= link_to " (delete)", "/users/#{@current_user.id}/projects/#{@project.id}/shifts/#{shift.id}", :method => :delete

%p= link_to "Add another shift", "/users/#{@project.user_id}/projects/#{@project.id}/shifts/new"

= link_to "Back to project", "/users/#{params[:user_id]}/projects/#{params[:project_id]}"

app/views/shifts/new.html.haml
%p= "Add shift to #{@project.name}"

= form_tag user_project_shifts_path, :method => :post, :controller => 'shifts', :action => 'create' do

	%p= label :shift, :start_date, 'Start date'
	%p= datetime_select :shift, :start_date

	%p= label :shift, :end_date, 'End date'
	%p= datetime_select :shift, :end_date

	
	%p= hidden_field :shift, :project_id, :value => @project.id


	%p= submit_tag 'Add shift'

= if @shift.errors.any?
	%ul.Signup_errors
	= for message_error in @shift.errors.full_messages
		%li= message_error


= link_to "Back to project", "/users/#{params[:user_id]}/projects/#{params[:project_id]}"