config/routes.rb
Timemanagement::Application.routes.draw do




	
	
	resources :users do
		resources :projects do
			member do
				get 'finish'
				get 'resume'
			end
			resources :shifts
		end
	end
	
	root :to => "sessions#home"
	match "signup", :to => "users#new", via: [:get, :post]
	match "login", :to => "sessions#login", via: [:get]
	match "login", :to => "sessions#login_attempt", via: [:post]
	get "logout", :to => "sessions#logout"
	get "dashboard", :to => "sessions#dashboard"
	get "profile", :to => "sessions#profile"
	get "statistics", :to => "sessions#statistics"

	get 'auth/:provider/callback' => 'sessions#login_auth'
	get 'auth/failure' => 'sesions#failure'
	





end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	has_many :shifts, dependent: :destroy

	validates :name, :presence => true
	validates :user_id, :presence => true

	after_initialize :defaults

	def defaults
		self.finished = false if self.finished.nil?
	end

	def total_time

		@total_time = 0
		@project_shifts = Shift.where("project_id = ?",id)
		@project_shifts.each do |shift|
			@total_time += (shift.end_date - shift.start_date).round
		end
		return @total_time

	end

	def total_time_textual
		seconds = total_time
		if seconds == 0 then return "none" end
		mm, ss = seconds.divmod(60)
		hh, mm = mm.divmod(60)
		dd, hh = hh.divmod(24)
		@textual_time = ""
		@textual_time += "#{dd} " + 'day'.pluralize(dd) + ' ' unless dd == 0
		@textual_time += "#{hh} " + 'hour'.pluralize(hh) + ' ' unless hh == 0
		@textual_time += "#{mm} " + 'minute'.pluralize(mm) + ' ' unless mm == 0
		@textual_time += "#{ss} " + 'second'.pluralize(ss) + ' ' unless ss == 0
		return @textual_time
	end

	def finish
		self.update(finished: true)
	end

	def resume
		self.update(finished: false)
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	
	before_filter :check_user, :only => [:show, :new, :create, :destroy]

	def new
		@project = Project.new
		@current_user =  User.find session[:user_id]
	end

	def create
		@project = Project.new(params[:project].permit(:name, :description, :user_id))
		if @project.save
			flash[:notice] = "Project #{@project.name} created successfully."
			flash[:color] = "valid"
			redirect_to "/users/#{@project.user_id}/projects/#{@project.id}"
		else
			flash[:notice] = "Invalid project data"
			flash[:color] = "invalid"
			render "new"
		end

	end	

	def show
		@project = Project.find(params[:id])
	end

	def destroy
		@project_name = Project.find(params[:id]).name
		Project.destroy(params[:id])
		flash[:notice] = "Project #{@project_name} was deleted successfully."
		flash[:color] = "valid"
		redirect_to "/dashboard"
	end

	def edit
		@project = Project.find(params[:id])
	end

	def update
		@project = Project.find(params[:id])
		if @project.update(params[:project].permit(:name, :description, :user_id))
			redirect_to "/users/#{@project.user_id}/projects/#{@project.id}"
		else
			render 'edit'
		end
	end

	def finish
		@project = Project.find(params[:id])
		if @project.finished
			flash[:notice] = "Project #{@project.name} is already finished."
			flash[:color] = "invalid"
			redirect_to "/users/#{@project.user_id}/projects/#{@project.id}"
		else
			@project.finish
			redirect_to "/dashboard"
		end
	end

	def resume
		@project = Project.find(params[:id])
		if @project.finished
			@project.resume
			redirect_to "/users/#{@project.user_id}/projects/#{@project.id}"
		else
			puts "project ongoing"
			flash[:notice] = "Project #{@project.name} is ongoing."
			flash[:color] = "invalid"
			redirect_to "/users/#{@project.user_id}/projects/#{@project.id}"
		end
	end

	def check_user
		#check that user in session is the same as user in url
		if session[:user_id].to_i == params[:user_id].to_i
			return true
		else
			redirect_to(:controller => 'sessions' , :action => 'login')
			return false
		end
	end


end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/new.html.haml
%p New project:


= form_tag user_projects_path, :method => :post, :controller => 'projects', :action => 'create' do

	%p= label :project, :name, 'Name'
	%p= text_field :project, :name

	%p= label :project, :description, 'Description'
	%p= text_area :project, :description

	
	%p= hidden_field :project, :user_id, :value => @current_user.id


	%p= submit_tag 'Create project'

= if @project.errors.any?
	%ul.Signup_errors
	= for message_error in @project.errors.full_messages
		%li= message_error


= link_to "Back to dashboard", dashboard_path

app/views/projects/show.html.haml
%h3= @project.name
%p= @project.description
%p
	- if @project.total_time == 0
		You haven't spent time with this project yet.
	- else
		= "Total time spent in this project is #{@project.total_time_textual} "
		= link_to "(view or delete shifts)", "/users/#{@project.user_id}/projects/#{@project.id}/shifts/"

%p= link_to "Add a shift", "/users/#{@project.user_id}/projects/#{@project.id}/shifts/new"

%p
	- if @project.finished 
		%a= link_to "Resume project", "/users/#{@project.user_id}/projects/#{@project.id}/resume"
	- else
		%a= link_to "Finish project", "/users/#{@project.user_id}/projects/#{@project.id}/finish"


= column_chart Shift.where('project_id' => @project.id).group_by_day(:end_date, format: "%D", last: 7 ).sum(:duration), library: {backgroundColor: "#eee",vAxis: {title: 'Hours'}, title: "Activity on the last week"}

%p= link_to "Back to dashboard", dashboard_path