config/routes.rb
Timemanagement::Application.routes.draw do




	
	
	resources :users do
		resources :projects do
			member do
				get 'finish'
				get 'resume'
			end
			resources :shifts
		end
	end
	
	root :to => "sessions#home"
	match "signup", :to => "users#new", via: [:get, :post]
	match "login", :to => "sessions#login", via: [:get]
	match "login", :to => "sessions#login_attempt", via: [:post]
	get "logout", :to => "sessions#logout"
	get "dashboard", :to => "sessions#dashboard"
	get "profile", :to => "sessions#profile"
	get "statistics", :to => "sessions#statistics"

	get 'auth/:provider/callback' => 'sessions#login_auth'
	get 'auth/failure' => 'sesions#failure'
	





end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Time Management
    = stylesheet_link_tag 'application'
    = javascript_include_tag "http://www.google.com/jsapi", "chartkick"
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %meta{ :name => 'viewport', :content => 'width=device-width' }

  %body

    .wrapper
      %header.header
        %h1.title Time Management
        %p
          - if @current_user
            Logged in as #{@current_user.name}, 
            %a(title="Logout" href=logout_path) Logout

      %nav.nav
        %ul
          %li= link_to "Dashboard", dashboard_path
          %li= link_to "Profile", profile_path
          %li= link_to "Statistics", statistics_path
          %li= link_to "Logout", logout_path

      .main
        - if flash[:notice]
          #notice.message= flash[:notice]
        - elsif flash[:warning]
          #warning.message= flash[:warning]

        = yield

      %footer.footer
        %p Copyright 2014. Miguel Cabrera